version: "3.9"

services:
  flask-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: flask-api-prod
    restart: always
    ports:
      - "80:5000"
    environment: 
      FLASK_DEBUG: 0
      FLASK_APP: app/app.py
      FLASK_ENV: production
    networks:
      - production-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-api
    networks:
      - production-net

networks:
  production-net:
    driver: bridge