version: "3.9"

# Example: Flask API with PostgreSQL Database
services:
  flask-api:
    build: ..
    container_name: flask-api-with-db
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment: 
      FLASK_DEBUG: 1
      DATABASE_URL: postgresql://user:password@postgres:5432/mydb
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  # Optional: Database management tool
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge